### 행렬의 필요성 
- 현실 세계의 많은 문제를 행렬을 이용해 해결 가능. 
    - 배열 / 리스트 형태 또한 행렬의 형태라고 이야기 할 수 있음. 
    - 인공지능 / 데이터 분석 모두 행렬의 연산이 가능함. 
    - 예) 컴퓨터의 메모리 구조 / 표 형태의 데이터 / 이미지 ; 행렬로 표현이 가능 / 데이터 시각화 
- 행력로 해결할 수 없다면 해결하기 매우 어려운 문제일 수 있음.


### Numpy란? 
-  Numpy 는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구 
- 현실 셰게의 다양한 데이터는 배열 형태로 표현이 가능함. 
- Python 기본 List에 비해 빠르고 강력한 기능을 제공함. 

### Numpy 차원 
- 1차원 축(행) : Vector
- 2차원 축(열) : Matrix
- 3차원 축(채널) : Axis 2 -> Tensor(3차원 이상)

In [6]:
import numpy as np           
list_data= [1,2,3]
array = np.array(list_data)

print(array)
print(array.size)
print(array.dtype)
print(array[2])

[1 2 3]
3
int64
3


In [14]:
# 0부터 3까지 배열 만들기 
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype = float)
print(array2)

array3 = np.ones((3,3), dtype = float) 
                 

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
array1 = np.arange(0,8).reshape(2,4)
array1

array2 = np.arange(0,8).reshape(2,4)
array2

array3 = np.concatenate([array1, array2], axis = 0)
array4 = np.arange(0,4).reshape(4,1)
print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [31]:
array1= np.arange(16).reshape(4,4)
array1

array2= array1 <10
array1[array2] = 100
array1

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100,  10,  11],
       [ 12,  13,  14,  15]])

In [32]:
array = np.arange(16,).reshape(4,4)

In [37]:
array = np.arange(0,10)
np.save('saved.npy',array)
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]
