<a href="https://colab.research.google.com/github/Soomin-Maxwell/Medical_AI_study/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy 

- Data could be represented with the form of array. 
- Dimension
 - 1 : axis 0 / Vector 
 - 2 : axis 1 / Maxrix 
 - 3 : axis 2 / Channel 




In [2]:
import numpy as np

In [8]:
list_data = [1,2,3]
array = np.array(list_data)

print(array.size)

3


In [18]:
# arange, dtype

array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype = int)
print(array2)

array3 = np.ones((3,3), dtype = str)
print(array3)

[0 1 2 3]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [28]:
# Concatenate
array4 = np.random.randint(0,10,(3,3))
print(array4)

array5 = np.random.normal(0,1,(3,3)) # ?
print(array5)

[[5 8 7]
 [6 3 0]
 [2 1 0]]
[[ 1.15430009  0.38471756 -0.23522938]
 [ 0.42203154 -0.39078285 -1.26353971]
 [ 0.77492158  0.40420109  1.0410753 ]]


In [33]:
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])
array8 = np.concatenate([array6,array7])

print(array8.shape)

(6,)


In [38]:
# Change shape
array9 = np.array([1,2,3,4]).reshape(2,2)
print(array9)

[[1 2]
 [3 4]]


In [46]:
arrayA = np.arange(8).reshape(2,4)
left,right = np.split(arrayA, [2], axis=1)

print(left.shape)
print(right.shape)
print(arrayA)
print(left)
print(right)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [58]:
# Calculation / Broadcasting 
arrayB = np.random.randint(1,10, size=4).reshape(2,2)
arrayC = np.arange(2).reshape(2,1)
print(arrayB)
print(arrayC)
print(arrayB + arrayC)

[[8 2]
 [4 6]]
[[0]
 [1]]
[[8 2]
 [5 7]]


In [74]:
# Masking 
arrayD = arrayB > 5
print(arrayD)
print('-' * 30)
arrayB[arrayD] = 100
print(arrayB)
print('-' * 30)
print(arrayB[arrayD])

[[ True False]
 [False  True]]
------------------------------
[[100   2]
 [  4 100]]
------------------------------
[100 100]


In [81]:
 # Sum
 arrayE = np.arange(16).reshape(4,4)
 print(arrayE)
 print('SUM:', np.sum(arrayE, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
SUM: [24 28 32 36]


In [86]:
# Save and Laod files 
array = np.arange(0,10)
np.save("saved.npy", array)
result = np.load("saved.npy")
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
arrayF = np.arange(0,10)
arrayG = np.arange(10,20)
np.savez("saved.npz", array1= arrayF, array2=arrayG)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [133]:
array = np.array([4,9,3,2,6,10])
array.sort()
print(array[::-1])

arrayH = np.array([[3,5,9,19,2,4],[2,7,3,8,1,2]])
print(arrayH)
arrayI = np.sort(arrayH)
print(arrayI)

[10  9  6  4  3  2]
[[ 3  5  9 19  2  4]
 [ 2  7  3  8  1  2]]
[[ 2  3  4  5  9 19]
 [ 1  2  2  3  7  8]]


In [108]:
arrayJ = np.linspace(0,10,5)
arrayJ

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [123]:
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

[[4 9 6]
 [3 3 7]]


In [124]:
arrayK = np.arange(0,10)
arrayL = arrayK
array[0] = 99
print(array)

[99.   2.5  5.   7.5 10. ]


In [129]:
#Remove duplicated
arrayM = np.array([1,1,2,2,2,3,3,4])
print(np.unique(arrayM))

[1 2 3 4]
